"""Initial migration.

Revision ID: 011695fbf3fb
Revises: 
Create Date: 2024-07-24 14:59:26.693238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011695fbf3fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employees')
    # ### end Alembic commands ###
