"""rename address

Revision ID: 59da0cb78a2e
Revises: 95d84f7275c4
Create Date: 2024-07-24 15:42:37.285824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59da0cb78a2e'
down_revision = '95d84f7275c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
